### ISSUE TITLE
Flagging is not working

### ISSUE THREAD

**Issue by Absentia** [chat-sdk/chat-sdk-ios#101]
As was mentioned in another post, flagging seems to be broken at the moment.  The current functionality I'm experiencing is that I swipe a message left to reveal the orange "Flag" button, and then when I tap the button the message slides back over and nothing changes.  If I swipe the message to the left again, the "Flag" button still appears. (I'm assuming it should say "Unflag" after it's already flagged?)  Most importantly, the supposedly flagged messages are not showing up on my Firebase database.

I've dropped a few breakpoints and all of the methods seem to be firing so I'm not sure what the issue is.  An Xcode search for "setMessageFlagged" brings up a couple of important looking lines of code, so I'm hoping somebody smarter can figure out what to do with them

**Comment by CalvinTp** [comment]
Hi,
I have found previously, there are 2 issues in total. 

**Issue 1:**
Inside ElmChatViewController, the code is passing in Int (integer) value but the method is expecting BOOL inside BChatViewController 

```
 [delegate setMessageFlagged:message isFlagged:message.flagged.intValue].thenOnMain(^id(id success) {

-(RXPromise *) setMessageFlagged: (id<PElmMessage>) message isFlagged: (BOOL) flagged {

```

**Issue 2:**
The polarity is inverted because when the message flag is not set, that is where you wanted the flag the message. But in this case, when the message is not set (which is 0), it will call unflagMessage and when the message is already flag (which is 1), it will cause flag message. 

```

-(RXPromise *) setMessageFlagged: (id<PElmMessage>) message isFlagged: (BOOL) flagged {
    if (flagged) {
        return [NM.moderation flagMessage:message.entityID];
    }
    else {
        return [NM.moderation unflagMessage:message.entityID];
    }
}

```
I believe fixing these 2 issues will resolve your issue.

I am using the flag for other functionality and have to recode this portions hence I am not able to provide the fix but only able to share what I have found previously. Hope it helps. 

Thanks,
Calvin

**Comment by simonsmiley64** [comment]
Hi @Absentia,

Quick thanks to @CalvinTp for his answer to this, hopefully you have managed to fix the issue as his answer is all correct. 

I have just downloaded the master and tested this and can now confirm parts of his answer and let you know a definite fix with the current code. Below you will see the current code:

```
-(RXPromise *) setMessageFlagged: (id<PElmMessage>) message isFlagged: (BOOL) flagged {
    if (flagged) {
        return [[BNetworkManager sharedManager].a.moderation flagMessage:message.entityID];
    }
    else {
        return [[BNetworkManager sharedManager].a.moderation unflagMessage:message.entityID];
    }
}
```

You can see that if the message is already flagged the we call the flagMessage function which keeps it flagged. The problem was that the messages would either stay flagged or never be set flagged. The fix to this is just switching them around:

```
-(RXPromise *) setMessageFlagged: (id<PElmMessage>) message isFlagged: (BOOL) flagged {
    if (flagged) {
        return [[BNetworkManager sharedManager].a.moderation unflagMessage:message.entityID];
    }
    else {
        return [[BNetworkManager sharedManager].a.moderation flagMessage:message.entityID];
    }
}
```

I tested this on the chat-sdk-v4 database and it seems to be working completely as expected with flagging and unflagging. 

**Note:** It is worth noting @CalvinTp's first answer is not actually an issue. We are setting an integer value of 0 or 1, these are directly related to a TRUE and FALSE BOOL meaning that iOS will deal with them appropriately. We recommend storing integers in the database and using them where possible as it avoids us, considering we can't store a BOOL in JSON, it keeps us from adding complexity and converting between the two. 

I am going to push this fix as a push request to the Chat SDK repository but it should be easy for you to modify this code yourself to enable the fix.

Simon

**Comment by simonsmiley64** [comment]
**Note:** I am rebasing the bug_fixes branch to the latest version of the code so the code to copy in is below:

```
-(RXPromise *) setMessageFlagged: (id<PElmMessage>) message isFlagged: (BOOL) flagged {
    if (flagged) {
        return [NM.moderation unflagMessage:message.entityID];
    }
    else {
        return [NM.moderation flagMessage:message.entityID];
    }
}
```

Same concept but slightly different code.

Simon

**Note:** I have tested this fix with both the new and slightly older versions of the code and both appear to be working as expected.

**Comment by Absentia** [comment]
Awesome thanks a lot guys.  Got it working perfectly now
