### ISSUE TITLE
Contact Module Can't Find any Contacts

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#103]
OK -

So now that the rest of my app is 90% done I started to focus back on Chat. Out of the gate the Stickers didn't compile though the fix stated in another thread did fix that, but now by Phonebook can't find any contacts.

Thoughts? How does one get notified of changes to the modules?

**Comment by jimijon** [comment]
Hows this coming?

**Comment by simonsmiley64** [comment]
Hi @jimijon,

Can you please give us a bit more information on the specific problem? 

The contacts book module downloads your contacts from the phone and then checks if there are any users with the same name, email or phone number currently registered to your Chat SDK database. 

This means in test conditions you need to create some users and ensure they have the correct details. 

It is worth checking a few things:

1. Does your contact book have many foreign numbers? (+44, +61 etc). It would be worth checking if the number is being found but if the check is not working due to how the number is stored.
2. Is your contact book being downloaded? When you load up the contact module it should request access to the contact book, if you clicked no it might still be not allowing the app to access your contact details.
3. Are you clicking the right option, click the + button and you should be able to choose between "search by name" and "search by contact book". If this second option isn't appearing there might be a problem with the configuration.

It might be that you don't have the latest version but if the project is configuring with it in then hopefully you are up to date. Now we need to see why the contacts are not being returned. 

If you can check over these things and get back to me we can hone in on the problem and get it resolved for you,

Simon

**Comment by CalvinTp** [comment]
Hi,
I am just responding incase it would help this thread. 

@jimijon are you using the latest code base? 

Inside BFirebaseSearchHandler:
```
-(RXPromise *) usersForIndexes: (NSArray *) indexes withValue: (NSString *) value limit: (int) limit userAdded: (void(^)(id<PUser> user)) userAdded {
```

There is a fix that solve searching for phone, emails, etc. If you are not using the latest code, you can add the following code directly:
```
    if(!indexes) {
        indexes = @[bNameKey, bEmailKey, bPhoneKey];
    }
```

I found this issue previously and was tied up with a lot of coding and before I could submitted an issue to fix the code in GitHub page, Ben/ Simon has fixed this issue on the code they have released. 

Just incase you are not using the latest code. If you are using the latest, how do you test the phone search? 

Thanks,
Calvin

**Comment by jimijon** [comment]
I click + in contacts.
I tap Phonebook. 
A modal comes up titled "Add users". 
I see on previously saved user.
I tap "add" and a new modal appears to "Search" with nothing in the panel.
I never, ever see my contact book.

**Comment by bensmiley** [comment]
The search module will search based on the details stored in the phone book. For example the contacts phone number and email address. Can you verify that there is a user that exists in the Firebase database that has a phone number or email address which also exists in the contacts? The email address or phone number needs to be exactly the same. For example, if the phone number is stored as +4445654... in the contact book and as 04564... in Firebase, there will be no match.

**Comment by 3r1k83** [comment]
I have the same problem. 
I downloaded the last version, and installed. I did the setup in my firebase project. 
The chat is working good, but I cannot find any contact. When I try to search or add a user I cannot find anything, and the method usersForIndexes in BFirebaseSearchHandler is never called during the search. 
![Simulator Screen Shot - iPhone 11 - 2019-12-09 at 12 18 00](https://user-images.githubusercontent.com/1701567/70431811-1f352700-1a7e-11ea-89fd-ba66c7810bd1.png)
