### ISSUE TITLE
Speaking of blocking and flagging....

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#104]
Is there a way to create "moderators?"

**Comment by simonsmiley64** [comment]
Hi @jimijon,

There is a way to create moderators. This is something on our long list of additions to make but lately we have been fixing up the Android version and Web version so I can't see it being implemented in the near future. 

You could though create it yourself without too much difficulty. 

1. Modify the threads code to include a "moderators" path. You would then add an array which would store the users entityIDs. We would use an array so there could be multiple moderators instead of only being able to have 1. 
2. Modify the thread download code to add this data to the thread core data objects. It should be easy to copy similar code for the other aspects. You'll need to remember to add this in the coredata code too: thread.moderators.

These two steps are straight forward, we modify the upload code and then the download code. Now we should have an array attached to the thread on the database and on the phone database. Initially you will want the thread creator to be the moderator so you can just use @[user.entityID] to be your array. You can then work out adding and removing later. 

3. You now need to change the functionality to allow moderators to do things others can't. To do this you will check the thread.moderators to get the array. Then check if your entityID is contained in it. If yes enable button/function, if no you don't.

This functionality should be structured in the same way the current code has been architected. Most of the cost can be copied and then modified to reflect moderators. 

For example:

`-(RXPromise *) addUserWithEntityID: (NSString *) entityID {`

Is doing just what you want but adding it to a user array. You can modify this to add it to the moderator path instead. 

Hopefully this helps you, if you do develop it and want to submit a pull request we can check and then add it to the overall project. This will mean the functionality will be updated and tested as we release newer versions.

Simon
