### ISSUE TITLE
blocking mechanism needed for app approval

### ISSUE THREAD

**Issue by Absentia** [chat-sdk/chat-sdk-ios#112]
I know this has been mentioned in a previous thread, but as the issue still remains unresolved I figured I would open a ticket dedicated specifically to the implementation of a feature that allows users to block each other.

Some of you may or may not know that Apple REQUIRES that users have the ability to block other users whom they deem offensive.  My app that features Chat SDK just got rejected for the following reason:

"Guideline 1.2 - Safety - User Generated Content

Your app enables the display of user-generated content but does not have the proper precautions in place.

Specifically, we were unable to locate a user-facing blocking mechanism separate from the report button where users can block abusive users themselves."

I have also received numerous rejections for this reason in the past while using other chat sdks.  This is something that, in my experience, Apple reviewers will catch and reject your app for 8 times out of 10.  The point I'm trying to make is that this is an extremely important issue.  Not being able to get apps approved makes the SDK worthless.

I know there was a report that a blocking feature was in the works and almost ready, but that was about a month ago and there has been no further information.  Should I expect that this feature will be added soon?

**Comment by RyanElliott94** [comment]
I've been meaning to email my blocking code but i have been really busy lately but if i have time i can email you the code i use to block and unblock people.

I can also send the code i use to check if a user is blocked and how to automatically delete new conversations. 

Now my code is by no means clean or even ideal for long time use but it does work!

Ryan

**Comment by Absentia** [comment]
I sent an email yesterday to the email address you have associated with your user profile.  If you get a chance to send me that code I will definitely appreciate it...otherwise I'm fine waiting for the official update.

**Comment by jimijon** [comment]
Please send me the code too!

**Comment by CalvinTp** [comment]
Hi Ryan,
I am interested in the code as well for my app. Could you send me the code also? 

Thanks,
Calvin

**Comment by RyanElliott94** [comment]
@Absentia @jimijon I have emailed you both the code, hopefully it will be all you need but as i said in the email, if you need more then let me know.

@CalvinTp I couldn't see you email on your profile but if you give me your email, i will send it to you too!

Thanks

**Comment by CalvinTp** [comment]
@RyanElliott94 , I have just dropped you an email :)

**Comment by Absentia** [comment]
Thanks a lot man!  I really appreciate it. My hard drive died so I'm gonna have to wait a couple days before trying it out.  I'll let you know how it goes

**Comment by jimijon** [comment]
Getting back from vacation soon. :-(   Will check on Friday... thanks ahead of time.

**Comment by RyanElliott94** [comment]
Hi @jimijon, Yeah sorry, i forgot to mention that I'm using an old version of the SDK because i can't figure out how to update to the latest SDK without losing all my own code! But to fix this issue, you need to replace that line with this `[self.model addMessage:message.model];`.

I use that code when i block a user from the contacts list so when a user is blocked, they will automatically be deleted after they have been blocked. You will need to ignore the second delete method as i add and view contacts differently to standard way, i just forgot to remove it but the first method should work as normal!

You can also ignore `(^id(MBProgressHUD * hud)` because that doesn't actually do anything.

**Comment by RyanElliott94** [comment]
@Absentia @jimijon @CalvinTp 

Okay so it seems i completely forgot to add some other code to my email so to make things easier, i will post it here!.

You would have noticed that there was some methods missing for blocking, unblocking and for showing a list of blocked user.

To fix this, you need to add these.

To go inside BBaseContactHandler.m:


    -(RXPromise *) addBlockedUser: (id<PUser>) contact withType: (bUserConnectionType) type {
    id<PUserConnection> connection = [[BStorageManager sharedManager].a fetchOrCreateEntityWithID:contact.entityID withType:bUserConnectionEntity];
    [connection setType:@(bUserConnectionTypeBlocked)];
    [connection setEntityID:contact.entityID];
    [[BNetworkManager sharedManager].a.core.currentUserModel addConnection:connection];
    return [RXPromise resolveWithResult:Nil];
    }

////

    -(RXPromise *) deleteBlockedUser: (id<PUser>) user {
    // Clear down the old blocking list
    id<PUser> currentUser = [BNetworkManager sharedManager].a.core.currentUserModel;
   
    NSPredicate * predicate;
    if (user && user.entityID) {
        predicate = [NSPredicate predicateWithFormat:@"type = %@ AND owner = %@ AND entityID = %@", @(bUserConnectionTypeBlocked), currentUser, user.entityID];
    }
    else {
        predicate = [NSPredicate predicateWithFormat:@"type = %@ AND owner = %@", @(bUserConnectionTypeBlocked), currentUser];
    }
    NSArray * entities = [[BStorageManager sharedManager].a fetchEntitiesWithName:bUserConnectionEntity withPredicate:predicate];
    [[BStorageManager sharedManager].a deleteEntities:entities];
    return [RXPromise resolveWithResult:Nil];
     }

That should definitely be it now!.

Sorry if it caused any of you any problems, it just slipped my mind!

Ryan

**Comment by jimijon** [comment]
Well... I sort of gave up. I then proceeded to purchase an iOS integration project with the requirement that flagging/unflagging, blocking/unblocking be part of core. Hopefully they will be able to jump start it with your code.

**Comment by orino76** [comment]
Hi Ryan,

I have read the code snippet you sent to me. So my understanding is that your simply ignore incoming messages from the blocked user and hence the user won't get notified.

I was checking the implementation on Line app, when the user unblock his friend, he won't be able to see the messages sent during the blocking period. And my guessing is that your implementation will reveal the past messages after the user unblock his friend. This behavior might not be desirable.

Kindly help to correct me if I am wrong. 

Cecil

**Comment by RyanElliott94** [comment]
Hello @orino76,

Yes, when an incoming message from a blocked user comes in, the user will not be notified and the conversation will automatically be deleted.

That means, even if the user is unblocked, any messages that were sent whilst they were blocked will not come through.

If you want any new messages from the blocked user to come in once they're unblocked, i would suggest you remove the line which will delete the conversation and try check for any new conversations that haven't come through.

Hope that all helps you!

Ryan

**Comment by orino76** [comment]
Hi Ryan,

The is another thing that matters is that if the conversation is not removed, we need to make sure that the user won't see the past messages after he reinstalls the app. So I ended up saving the blocking information under each message just like read receipt. In this way we can make sure that those messages during blocking period won't come thru but new messages will even if the user reinstalls the app. 

The followings are my changes made for blocking messages. I used my own BlockingHandler as I managed my contacts independently so I won't go through this part.

In CCMessageWrapper.h, I added a property `blocked` to indicate if the message should be ignored or not.

and to set this value, in CCMessageWrapper.m, I added the following in deserialize function.
`          NSDictionary *blocklists = value["blocked"];
            if (blocklists) {
                NSDictionary * userBlockedStatus = blocklists[[NM.core.currentUserModel entityID]];
                _blocked = [userBlockedStatus["blocked"] intValue];
            }
`

and I also added the following function so that the message can be set to blocked if the sender is blocked.

`-(RXPromise *) setBlock: (id<PThread>) thread {
    RXPromise * promise = [RXPromise new];
    
    NSDictionary * data = @{[NM.core currentUserModel].entityID: @{bBlockedPath: @YES}};
    
    FIRDatabaseReference * ref = [[[FIRDatabaseReference threadMessagesRef:thread.entityID] child:_model.entityID] child:bBlockedPath];
    [ref updateChildValues:data withCompletionBlock:^(NSError * error, FIRDatabaseReference * ref) {
        if (!error) {
            [promise resolveWithResult:Nil];
        }
        else {
            [promise rejectWithReason:error];
        }
    }];
    return promise;
}
`

And in `messagesOn` function in CCThreadWrapper.m, I added the following lines when the observer is called.
`
                    if (message.blocked) {
                        [promise resolveWithResult:self];
                        return;
                    }
                    else if ([NM.blocking isBlocked:message.model.userModel]) {
                        if (!message.blocked) {
                            [message setBlock: self.model];
                        }
                        [promise resolveWithResult:self];
                        return;
                    }
`

what it does is that drop messages marked blocked and if the sender is blocked then the message is marked blocked.

Note that I only allow blocking function in 1-to-1 thread as that's common practice for other chatting apps.

Kindly let me know if there is any issue in my code. Thanks,
Cecil

**Comment by RyanElliott94** [comment]
Hello again @orino76,

Looking at your code, it seems fine. I haven't tested it because i haven't got time but again i don't see any problems.

I feel like i should explain that with my own personal app, i have 2 deletion methods. The 1st one is the standard SDK way and the 2nd will not only delete the conversation from the local device but removes all traces of that conversation from Firebase and that's why my own blocking code is the way it is so when the conversation is deleted, the entire conversation will be removed so it will never reach the other user even if they re install the app.

Sorry my own code couldn't be of any use to you but i hope it helped you with you're own code!

Ryan

**Comment by bensmiley** [comment]
For anyone who's interested, we've now released a blocking module - available [here](https://chatsdk.co/downloads/user-blocking-for-ios/). This module is also compatible with [Chat SDK Web](https://github.com/chat-sdk/chat-sdk-web).
