### ISSUE TITLE
Logout button crashing

### ISSUE THREAD

**Issue by RyanElliott94** [chat-sdk/chat-sdk-ios#120]
I don't know why but every now and again the logout button will completely crash the app. I haven't changed the logout code so it's nothing I've done.

I also don't get much information in the debugger becasue all i get is this `*** Terminating app due to uncaught exception of class 'Fault'
libc++abi.dylib: terminating with uncaught exception of type Fault`. I also added some breakpoints in the hope i could find more info about it but i can't.

Any help would be appreciated!

Thanks,
Ryan

**Comment by simonsmiley64** [comment]
Have you added an "all exception" break point? This should show you where the error is coming from or at least give you more information.

<img width="298" alt="screen shot 2017-08-25 at 09 25 20" src="https://user-images.githubusercontent.com/8721425/29693142-61dc22b0-8977-11e7-8e53-3acbc4140a28.png">
<img width="296" alt="screen shot 2017-08-25 at 09 25 37" src="https://user-images.githubusercontent.com/8721425/29693143-61e743d4-8977-11e7-90b6-cad2bb8d8261.png">

The crash is potentially being caused by not being correctly authenticated to the app, if you have changed the login code then this might affect the logout code. 

Let me know if the exception breakpoint gives you more information as the current error doesn't give us much to go on.

Simon

**Comment by RyanElliott94** [comment]
I done that and i got this

    Voice`-[Invoker invokeSync:method:args:]:
    0x1091215ea <+0>:   pushq  %rbp
    0x1091215eb <+1>:   movq   %rsp, %rbp
    0x1091215ee <+4>:   pushq  %r14
    0x1091215f0 <+6>:   pushq  %rbx
    0x1091215f1 <+7>:   movq   %rdi, %rbx
    0x1091215f4 <+10>:  movq   0x33c68d(%rip), %rax      ; Invoker.client
    0x1091215fb <+17>:  movq   (%rbx,%rax), %rdi
    0x1091215ff <+21>:  movq   0x32bcba(%rip), %rsi      ; "invoke:method:args:"
    0x109121606 <+28>:  callq  *0x26d0ec(%rip)           ; (void *)0x0000000110760ac0: objc_msgSend
    0x10912160c <+34>:  movq   %rax, %r14
    0x10912160f <+37>:  movq   0x33c67a(%rip), %rax      ; Invoker._throwException
    0x109121616 <+44>:  cmpb   $0x0, (%rbx,%rax)
    0x10912161a <+48>:  je     0x109121646               ; <+92> at Invoker.m:120
    0x10912161c <+50>:  movq   0x339245(%rip), %rdi      ; (void *)0x0000000109464e78: Fault
    0x109121623 <+57>:  movq   0x32b866(%rip), %rsi      ; "class"
    0x10912162a <+64>:  movq   0x26d0c7(%rip), %rbx      ; (void *)0x0000000110760ac0: objc_msgSend
    0x109121631 <+71>:  callq  *%rbx
    0x109121633 <+73>:  movq   0x32b8be(%rip), %rsi      ; "isKindOfClass:"
    0x10912163a <+80>:  movq   %r14, %rdi
    0x10912163d <+83>:  movq   %rax, %rdx
    0x109121640 <+86>:  callq  *%rbx
    0x109121642 <+88>:  testb  %al, %al
    0x109121644 <+90>:  jne    0x10912164e               ; <+100> at Invoker.m:118
    0x109121646 <+92>:  movq   %r14, %rax
    0x109121649 <+95>:  popq   %rbx
    0x10912164a <+96>:  popq   %r14
    0x10912164c <+98>:  popq   %rbp
    0x10912164d <+99>:  retq   
    0x10912164e <+100>: movq   %r14, %rdi
    0x109121651 <+103>: callq  0x1092f821a               ; symbol stub for: objc_exception_throw

**Comment by RyanElliott94** [comment]
Right I'm going to close this issue because I've managed to fix it. It turns out it was just a single line of code that i uncommented on BBackendlessPushHandler.m so it was of my own doing!

Thanks,
Ryan
