### ISSUE TITLE
iOS 11.0 / Swift : Undefined symbols for architecture x86_64:   "_OBJC_CLASS_$_BFirebaseNetworkAdapter"

### ISSUE THREAD

**Issue by cesariel** [chat-sdk/chat-sdk-ios#128]
Hi!

I cannot resolve this issue:

<img width="588" alt="screen shot 2017-09-21 at 4 04 55 am" src="https://user-images.githubusercontent.com/13699157/30685188-0ee54c2e-9e82-11e7-9595-1b6de7e03d10.png">

**Comment by simonsmiley64** [comment]
Hi @cesariel,

In order to troubleshoot this it would be useful to know a few more details.

1. Does this issue happen when using other iOS versions? It would be useful to run your project on the simulator with iOS 10 and 9 to check. This will let me know whether this is a new issue with the latest iOS I need to fix.

2. Are you setting your project up correctly?

a) First thing to check here is whether the Chat SDK runs when you just download it straight from Github. If it does you know that the code is good but the configuration went wrong somewhere. If it doesn't work straight from the box then it is an issue at our end which I can look into and fix. 

b) Next thing to check is whether you have completed the steps correctly. I would recommend using [this](https://www.youtube.com/watch?v=3OWF_qyieXQ) video and the latest readMe in Github. We have recently released an update and are still in the process of updating some of our wiki documentation. I put this video together just over a week ago so should be an up-to-date explanation of adding the Chat SDK to your project. 

Let me know how these two suggestions go, I expect it will be to do with using the latest set up instructions as we have recently changed our set up and where the BFirebaseNetworkAdapter code is located. 

Let me know if I can be of further help,

Simon

**Comment by cesariel** [comment]
I will mark this Issue as Closed! Was my fault. When I copied the ClassFirebaseAdapter folder to the Proyect, the Target was not selected. So to fix the Problem:

Build Phases --> Compiler Sources -> add all the .m files --> Clean/ Build

Everything good now! Thanks for the quick response.
