### ISSUE TITLE
Best way to download update to fix crash on iOS11 

### ISSUE THREAD

**Issue by Allansk2** [chat-sdk/chat-sdk-ios#135]
Thanks to the team, the issue #130  has been fixed, but since I download the Chat SDK and add to my project, I modified some files in Chat SDK to fit my need, what would be the best way to get the update without overwriting my changes or redo all my changes. Thanks!

**Comment by simonsmiley64** [comment]
Hi @Allansk2,

I have been meaning to create a video tutorial on making modifications to the Chat SDK but haven't had the time recently. I will briefly go through the correct way of modifying the Chat SDK.

Ideally you don't want to be changing any of the Chat SDK files. The Chat SDK should almost be like a library attached to your project which you can access but isn't changed. This then allows you to swap out the old version and add in new versions without trouble. 

The way you do this is by subclassing the views in the Chat SDK. For example if you want to show the BChatViewController you first subclass it: BAllanChatViewController and then add in the functions you want to change. You then load it instead of the original viewController. The nature of a subclass is that it will run the functions from the parent unless we have a function in the subclass. You can also call [super functionName] to continue to call the parent function and just add a snippet of new code in the subclass. 

Obviously there are going to be some views which are more tricky to subclass (changing the appTabBar viewControllers requires you to subclass the BAbstractAdapter) but this comes from knowledge of the Chat SDK which you'll get by using it and we can also help you with it too. 

I would propose the following:

1. Download a new project and add the latest Chat SDK
2. Look at the additional pieces of code you have added, try to add them in the correct way by subclassing 
3. Ask us for help and clarification if you need it.

Hopefully you don't have a huge amount of code to be changed much of it should be able to be copy pasted. The reason I suggest this is as your project and modifications get bigger the harder it will be to replace the Chat SDK versions. We have a lot of new content in the pipelines (mention functionality, thread administrators, URL messages, commenting with photo messages, upgrades to current functionality) all which might change the master version of the code. It is better to be coding your project correctly from the start than have to unpick a years worth of work if iOS 12 requires similar upgrades as iOS 11 did.

Hopefully this answers your question. Post on this thread if you need any advice or you can get some priority support for more technical things,

Simon

**Comment by bensmiley** [comment]
@Allansk2 Depending on how you've modified the files, you may be able to merge the latest version of the Chat SDK with your project. Otherwise, you could use FileMerge to find which changes you've made and port them manually. As Simon said, it's better practice to subclass the Chat SDK files rather than modify them. However, if you do want to modify them, you should fork the Chat SDK project and make your modifications on that fork. Then include the Chat SDK in your project using CocoaPods development pods and symlinks for the Firebase dependent modules. Then you can just merge the latest version of the library with your fork when new updates come out.
