### ISSUE TITLE
Integration of chat SDK to existing project

### ISSUE THREAD

**Issue by Meet1313** [chat-sdk/chat-sdk-ios#136]
hi Ben,

I have integrated chat SDK to my existing project and its working like a charm! but what problem I am facing is i can't access my swift files(.swift) in development pods.

My project is in swift.  for example i want to refer the class file(viewcontroller.swift) in chat sdk pod file. please help me out.

**Comment by bensmiley** [comment]
This is due to the project hierarchy. Your project is dependent on the Chat SDK pods but they are not dependent on your app. Really, it's not a good idea to modify the Chat SDK files directly. It's much better to subclass them. I'd recommend looking over the [wiki](https://github.com/chat-sdk/chat-sdk-ios/wiki) there are some guides on how to do this. If you really want to access your files from the Chat SDK then you would need to import all the files directly into Xcode.

**Comment by Meet1313** [comment]
I got error when Copy the ChatSDKFirebaseAdapter folder from
chat-sdk-ios/ChatSDK/ChatSDKFirebaseAdapter/Classes
<https://github.com/chat-sdk/chat-sdk-ios/tree/master/ChatSDK/ChatSDKFirebaseAdapter/Classes>
into
my Xcode project and i am not able to access

BFirebaseNetworkAdapter in my project and not able to access this method
DatabaseReference.userRef


I have attached Screen shot of error.
