### ISSUE TITLE
Override the Logout Button

### ISSUE THREAD

**Issue by cesariel** [chat-sdk/chat-sdk-ios#137]
It is posible to Override the Logout Button functionality on the Profile Tab?

**Comment by simonsmiley64** [comment]
Hi @cesariel,

Yes it is very easy to override the logout button. 

1. Subclass the profile view
2. Subclass the BDefaultInterfaceAdapter
3. Change the new interface adapter to be the adapter for the project in the app delegate:

    ```
// Set the default interface manager
    [BInterfaceManager sharedManager].a = [[BTedInterfaceAdapter alloc] init];
```
 
4. Update the new adapter to return the correct profile view:

```
-(NSArray *) defaultTabBarViewControllers {

    return @[self.privateThreadsViewController,
             self.contactsViewController,
             [self podcastViewController],
             [self newProfileViewControllerWithUser: Nil]];
}

-(UIViewController *) newProfileViewControllerWithUser: (id<PUser>) user {
    
    // Add in the code to load your own profile view here

    return controller;
}
```

5. Add in the new code to replace the logout button to do what you want

`self.navigationItem.rightBarButtonItem = [[UIBarButtonItem alloc] initWithTitle:[NSBundle t:bLogout] style:UIBarButtonItemStylePlain target:self action:@selector(newLogout)];`

It might be worth putting this in the viewDidAppear function and to still call `super viewDidAppear`

This will replace the current button with a new button (although some testing will be required)

It is also worth noting you need to make sure that the logout code is called somewhere otherwise the Chat SDK won't logout properly and you will probably encounter bugs. 

Hopefully this helps give you an idea of how this should work. All the code above is sudo code to help you know what to do and shouldn't be copy pasted into the code without thinking through what you are doing and why.

Simon
