### ISSUE TITLE
Facebook ID

### ISSUE THREAD

**Issue by GreenRollingHills** [chat-sdk/chat-sdk-ios#139]
Hello,

This is more of a question than an issue.  Shouldn't we be creating our own Facebook IDs and using them in our projects?  Why did you recommend in the "Integration with an existing project" directions that we use the one in your demo?

Thanks,

**Comment by bensmiley** [comment]
Yes, you should be creating your own accounts for social login and Firebase. Could you direct me to the location of the text where it says that you should use the demo Facebook ID? I think in the instructions it explains how to setup your own Facebook ID.

**Comment by simonsmiley64** [comment]
Hi @GreenRollingHills,

I have looked through the tutorial but I can't find where it explicitly says to use our test Facebook details. This would be false anyway since Facebook login links with the bundleID of your project meaning you have to create your own account and link it. 

If you look in the Chat SDK [wiki](https://github.com/chat-sdk/chat-sdk-ios/wiki) you can see that we have separate tutorials for adding the Chat SDK to your project, Firebase configuration and all the social media accounts. 

**Note:** We have recently finished updating the code, this means some of the tutorials might be slightly out of date. I am going to be updating them in the next few weeks. I would recommend using the Chat SDK ReadMe file currently as that has the latest configuration details.

Simon

**Comment by GreenRollingHills** [comment]
Thanks for your response,

here is the url: https://chatsdk.co/docs/ios-quickstart/

Under the firebase setup section:

> 10. Copy the following rows from the demo ChatSDK Info.plist file to your project's Info.plist
> App Transport Security Settings
> URL types
> FacebookAppID
> All the privacy rows. These will allow the app to access the camera, location and address book

**Comment by simonsmiley64** [comment]
Hi @GreenRollingHills,

This documentation shows you how to add the Chat SDK to your project. Adding all the different plist fields means you are ready to configure all the different additional features (Facebook, Twitter login etc). We have included them here so you can copy everything across and not get confused. 

If you checkout the Facebook tutorial we then walk through customising the FacebookAppID field there. 

This is similar to how the Chat SDK comes with the Facebook code in it. Just because you might not be using it now doesn't mean that you won't in the future. Adding all the Facebook code initially makes configuration easier as there are less troubleshooting issues - in this case it is very easy to forget to add the FacebookAppID row which then mysteriously disables Facebook. 

Simon
