### ISSUE TITLE
"FirebaseAnalytics/FirebaseAnalytics.h" - File not found

### ISSUE THREAD

**Issue by Mortenest** [chat-sdk/chat-sdk-ios#145]
Hi,

I have tried to install the ChatSDK as per the instructions via Cocoapod, but I really can't get my project to compile now due to ChatSDKFirebaseAdapter not being able to find FirebaseAnalytics.h from the Firebase.h file .

My pod file has a lot of dependencies where some need to use the use_frameworks! flag.

I'm really at a loss of what to do now. Hope somebody can help me.

- Morten

**Comment by simonsmiley64** [comment]
Hi @Mortenest,

Have you watched the tutorial video on our YouTube channel? You can find the v4.2.0 video [here](https://www.youtube.com/watch?v=3OWF_qyieXQ)

I would also recommend using the documentation in the ReadMe file? Adding the FirebaseAdapter file using Sim Links is the easiest way to do this but otherwise it is text documentation of the video added above. 

If you are getting Firebase.h not found issues this is because you have added the Chat SDK incorrectly. We are currently updating our documentation so it is important to ensure you are using the most up to date tutorials. 

Let me know if this helps or if I can help you further.

Simon

**Comment by Mortenest** [comment]
I found out that ChatSDKFirebaseAdapter had sneaked itself into the podfile, which when i doublechecked shouldn't have been there in the first place.

I don't know how it got in there, whether it's a legacy thing, or I just got a bit confused of how ChatSDK should be installed.

Nevertheless, I'm up to speed now.
Thanks.

**Comment by bensmiley** [comment]
Yes, that error happens if you try to include the `FirebaseNetworkAdapter` as a Podfile dependency. This is due to an issue with the Firebase pods and Cocoapods. We've contacted both and it doesn't look like there is a solution on the way any time soon.
