### ISSUE TITLE
custom login view controller init methods

### ISSUE THREAD

**Issue by GreenRollingHills** [chat-sdk/chat-sdk-ios#146]
Hello,

This is more of a question than an issue.   What should my custom login view controller init methods be? 

 I have created an xib for my custom login.  Is subclassing ElmLoginViewController correct?  if yes, then what should my init methods be?  In my subclass it must call a super init method.  And if I do I eventually call ElmLoginViewController's init method which creates the VC based on the nib name "BLoginViewController".  My custom xib has a different nibName.

Thanks,

**Comment by GreenRollingHills** [comment]
Hello,

So, I think I found the solution.  This is what I did:

```
- (id) initWithNibName:(NSString *)nibNameOrNil bundle:(NSBundle *)nibBundleOrNil {
    
    return self;
}

- (id)init
{
    
    self = [self initWithNibName:@"CustomLoginVC" bundle:[NSBundle mainBundle]];
    
    if (self) {
        
        self.delegate = self;
        
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillShow:) name:UIKeyboardWillShowNotification object:Nil];
        [[NSNotificationCenter defaultCenter] addObserver:self selector:@selector(keyboardWillHide:) name:UIKeyboardWillHideNotification object:Nil];
    }
    return self;
}
```

Then when I need it I did this:

`BNetworkManager.shared().a.auth().setChallenge(CustomLoginVC.init())`

in my testing it appears to work.  This ok?  Are there better solutions?  Thanks.

**Comment by simonsmiley64** [comment]
Hi @GreenRollingHills,

I have just loaded up a version of the Chat SDK and looked at the BLoginViewController, you seem to have most of the stuff required (set the delegate, set the challenge view controller etc).

The only other thing you might want to have would be these lines of code:

```
    // First check to see if the user is already authenticated
    [self showHUD: [NSBundle t:bAuthenticating]];
    [NM.auth authenticateWithCachedToken].thenOnMain(^id(id success) {
        [self authenticationFinished];
        return Nil;
    }, Nil);
```
These check whether the user is authenticated when the view is loaded. 
Note: It would be worth testing your current version with multiple login states to ensure the login view is always maintained even if there isn't an authenticated user available.

Otherwise though this seems to be the simplest solution and if everything is working this would be the one I would go with. 

Simon

**Comment by bensmiley** [comment]
If you are subclassing the `BLoginViewController` your code looks good. If you are subclassing the `ElmLoginViewController`, you would need to implement the `ElmLoginViewDelegate` and set `self.delegate = self` in the init method.
