### ISSUE TITLE
Server side integration

### ISSUE THREAD

**Issue by JoiiinPeter** [chat-sdk/chat-sdk-ios#147]
Hi,
we are looking to integrate the Chat SDK to our existing project. We have our own sign-up, login and authentication process, and group chat is depending on other features of our app. So, there might be some user cases that server would need to create users, threads, even sending system messages, etc. We are looking at some form of integration of our app server side backend to your chat.
I don't see any server side SDK/API provided to access chat data from server side. Are these kind of server side integration supported? If I integrate my server with Firebase directly through APIs provided by Google. Do you have any concern or anything I should aware?

Thanks a lot,
Peter.

**Comment by bensmiley** [comment]
Hi Peter,

Integration with your server is definitely possible. We've worked with a number of clients to do this - it's also on our TODO list to write some more documentation on the process. 

All the data that the Chat SDK writes to Firebase is accessible by the [Firebase REST API](https://firebase.google.com/docs/reference/rest/database/). This means that you can add and remove users, manage threads and send messages directly from your server. 

Because Firebase uses MongoDB, there isn't really a defined schema - the schema is defined by the client. My recommendation would be that you get a version of the Chat SDK running on your Firebase account and have a look at the data it generates. It's not particularly complex because there are only three entities - user, thread and message. 

Here's a simple example to get you started - sending a message via the REST API. 

1. First you would need to look at the message data in Firebase. It looks like this:

  ```
  JSON: "{\"text\":\"Message\"}"
  date: 1508419700664
  payload: "Message"
  type: 0
  user-firebase-id: "36CB7GWiXdWJhebm1WyjPhSDECk2"
  ```

And it's written to the `threads/[thread id]/messages/[message id]` path. 

2. You would need to create a function on your server which could write this kind of data to the relevant path in Firebase. The message should then appear on any devices that are members of that thread. 

3. There are any issues, first I'd recommend looking at the Chat SDK code - it's well written and clear so you should be able to get a sense of what's going on from looking at it. If you decide to use the SDK it is recommendable to get a feel for the code anyway because you will probably want to make some customizations. In this case, you can look at the [CCMessageWrapper](https://github.com/chat-sdk/chat-sdk-ios/blob/master/ChatSDKFirebaseAdapter/Classes/Firebase/CCMessageWrapper.m) class.

  ```
  -(RXPromise *) send {
      if (_model.thread) {
          return [self push].thenOnMain(^id(id success) {
              [[CCThreadWrapper threadWithModel:_model.thread] pushLastMessage:[self lastMessageData]].thenOnMain(^id(id success) {
                  return [BEntity pushThreadMessagesUpdated:_model.thread.entityID];
              },Nil);
              return success;
          }, Nil);
      }
      else {
          return [RXPromise rejectWithReason:Nil];
      }
  }
  ```
  This gives some extra context, when we sent a message we also need to set the `lastMessage` property on the parent thread. After we sent the message we need to update the `thread/updated/messages` timestamp. 

4. Look at the Firebase dashboard as you are are performing actions with the client. The data will update in realtime. In this case, you would see the new message being added and the `lastMessage` property being set and the timestamp being update. 

I hope this helps. If you have a more specific query you can post another issue.
