### ISSUE TITLE
Weird Behavior on iPhone X Sim

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#151]
See the image
![simulator screen shot - iphone x - 2017-11-01 at 17 27 58](https://user-images.githubusercontent.com/971445/32302910-43928d0c-bf33-11e7-862b-662360a18006.png)

**Comment by jimijon** [comment]
everything is left justified, color bubble are wrong, and the bottom margin is wrong.

**Comment by jimijon** [comment]
also notice the status bar ... the text is black.

**Comment by bensmiley** [comment]
Ok, this hasn't been tested on the iPhone X so far. I'll look into it.

**Comment by bensmiley** [comment]
I've looked into this issue and some problems are connected to the Chat SDK and some are specific to your app. 

I've added an extra margin at the bottom of the chat view and fixed some problems on other screens. 

The issue with the status bar seems to be related to the theme of your app. I also wasn't able to replicate the problem with the bubble alignment. 

These issues are fixed in version [4.3.8](https://github.com/chat-sdk/chat-sdk-ios/releases/tag/4.3.8).
