### ISSUE TITLE
Unread Count issue

### ISSUE THREAD

**Issue by chintan217** [chat-sdk/chat-sdk-ios#156]
When I login with some account and start chat with some account. and suppose total message count is 10. then I logout and login with same account in different device, Its says unread count is 10. It must be 0.

**Comment by bensmiley** [comment]
Currently, whether a message is read or not isn't stored on the server - only the device. That's why if you log in with a different device, it resets. This behavior isn't ideal but I think that it's a minor issue because usually, users will only access an app from their primary device. In most cases when they upgrade to a new device, they will transfer all their app settings at the same time. I'll add it as an enhancement request but it's relatively low priority.

**Comment by sanjaytalreja** [comment]
@bensmiley any update on this?we understand its on low priority but it is much needed when people reinstall the app in same device.
