### ISSUE TITLE
Backendless Push Notification not working for Swift version

### ISSUE THREAD

**Issue by Lavii7** [chat-sdk/chat-sdk-ios#16]
Noticed that the bakcendless push setup for swift not working( pod installation no issue) 
- however after doing all the things to setup the swift noticed that unless i am missing something the push notification not working for swift version. I am thinking maybe i am missing something in the code insertion part as the setup guide you guys have is for Objective -C. So please give some guidance 
thanks

**Comment by bensmiley** [comment]
Hi Lavii,

When you say push isn't working do you mean that there is a compilation issue or that the pushes aren't getting through? Do you have an error report or stack trace? 

Thanks,

Ben

**Comment by Lavii7** [comment]
Not a compilation issue after integrating per the instruction, after running on device, when messaging from device to device on iOS to iOS and iOS to android; when application is off from background, the push doesn't work at all meaning the Backend is not pushing. we have enabled the push on development on the provisional as well

**Comment by bensmiley** [comment]
This is a common issue. I expect that there is a certificate issue with iOS and that the Android app is being seen as online, so pushes aren't being sent.

Try killing the android app rather than just putting it in the background. Then verify if the user is flagged as offline by looking in the Firebase database (user/online path) or by adding a breakpoint to the push code in iOS. This will let you see if pushes are being requested correctly. You an confirm this by looking at the Backendless dashboard. 

With iOS -> iOS, this is usually caused because iOS has bugs around development push notifications. The app tends to cache old certificates so even when you add a new correct certificate, pushes still don't come through. These issues will resolve themselves when you test it on TestFlight.

**Comment by sachinrot** [comment]
Hello Ben,
first of all, thanks for such a great library.
I am facing somewhat similar issue with push notification, meaning , i have configured everything that backendless says but i am not receiving any push on my device. I do not have any compile time errors and my app works perfectly fine when i configured with my firebase account with regular chats. 
I have perfectly working push notification system from my own server so i dont think that my .12 file has any issues either. 
When i went to backendless dashboard then i saw that i dont have any devices registered there and i got curious and read into backendless documentation and they say  that i have call [backendless.messaging registerForRemoteNotifications]; in order to register my device and i couldnt see that code into demo apps that you guys provided, But since you guys said that we shouldnt add any code from backendless documentation and that you guys have already added that and all we have to do is to configure app settings and certificates so i did not bother about it But my push notifications are still not working.
Do i have to add backendless SDK seperately or is that already added in the pods install ? (i can see that you have added backendless in podinstall but still wan to double check)
Any help is greatly appreciated.
Thanks 
Sachin

**Comment by bensmiley** [comment]
Hi Sachin,

I've double checked the library and the code `registerForRemoteNotifications` is called in the `BBackendlessPushHandler` class. Can you put a breakpoint in this method and double it's being called correctly? Have you followed the instructions found [here](https://github.com/chat-sdk/chat-sdk-ios/blob/master/Docs/Modules/Backendless.md)?

Thanks,

Ben

**Comment by sachinrot** [comment]
Hello Ben, 
Thanks a lot for the reply although my problem was solved by something else.
Let me explain so that it helps others 
1) Yes you have to install backendless dependencies separately if you have downloaded the ChatSDK demo project from GitHub and trying to make that work (instead of integrating into your code directly)

2) My problem was resolved by reading the docs on backendless website, lot of people are facing Push issues and the simple solution is to close everything you are doing and recreate the certs from the beginning, i know this sounds crazy but i closed everything and recreated from scratch and it worked for some reason.
Thanks Ben

**Comment by bensmiley** [comment]
Thanks for the feedback.
