### ISSUE TITLE
ChatSDKFirebaseAdapter Module integration

### ISSUE THREAD

**Issue by pankti28** [chat-sdk/chat-sdk-ios#160]
I am not able to access any methods of ChatSDKFirebaseAdapter when I haved copied the ChatSDKFirebaseAdapter folder from chat-sdk-ios/ChatSDK/ChatSDKFirebaseAdapter/Classes into my Xcode project and I am not able to access 
BFirebaseNetworkAdapter in my project and not able to access this method DatabaseReference.userRef.

**Comment by bensmiley** [comment]
Can you verify that you've done the following:

- Add the Firebase Adapter files to your project folder
- Add the files from inside Xcode
- If you are using Swift, add the headers to your bridging header file

**Comment by pankti28** [comment]
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target ‘testproject’ do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 4.3’
pod 'NextGrowingTextView'
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'GooglePlacePicker'
pod 'UzysAssetsPickerController'
pod 'KFSwiftImageLoader', '~> 3.0'

  # Pods for testproject
#  pod "ChatSDK", :path => "../"
  pod "ChatSDKCore", :path => "../ChatSDK/ChatSDKCore"
  pod "ChatSDKUI", :path => "../ChatSDK/ChatSDKUI"
  pod "ChatSDKCoreData", :path => "../ChatSDK/ChatSDKCoreData"
  pod "ChatSDKFirebaseAdapter", :path => "../ChatSDK/ChatSDKFirebaseAdapter"

end

This is my podfile and I want to add push notifications in my project.
Thanks in advance.

**Comment by bensmiley** [comment]
The problem is that you can't add the `ChatSDKFirebaseAdapter` using CocoaPods. There is a description of the problem [here](https://github.com/chat-sdk/chat-sdk-ios/wiki/Issues-with-Firebase-Pods).

As a result, any code that depends on Firebase needs to be added to Xcode manually. [See instructions](https://github.com/chat-sdk/chat-sdk-ios#adding-the-chat-sdk-to-your-project):

### Adding the Chat SDK to your project

1. Add the Chat SDK development pods to your Podfile

  ```
  use_frameworks!
  pod "ChatSDK"
  ```

3. Add additional support pods. These are external pods that are needed by the Chat SDK

  ```
  pod "Firebase/Auth"  
  pod "Firebase/Database"  
  pod "Firebase/Messaging"  
  pod "Firebase/Storage"  
  ```
  
4. Run `pod install` or `pod update` to get the latest version of the code.

5. Copy the **ChatSDKFirebaseAdapter** folder from [chat-sdk-ios/ChatSDK/ChatSDKFirebaseAdapter/Classes](https://github.com/chat-sdk/chat-sdk-ios/tree/master/ChatSDK/ChatSDKFirebaseAdapter/Classes) into your Xcode project. From inside Xcode, right click in the left panel click **Add Files** and add the **ChatSDKFirebaseAdapter** folder.

  You can see how to add it via symlink [here](https://github.com/chat-sdk/chat-sdk-ios#adding-the-firebase-adapter-source-code).

**Comment by Meet1313** [comment]
Thank you @bensmiley. It was build error. I was trying to import the module which was not build properly , so unable to access the method of that module. 
Now, its working fine. thanks for your support . :) :) 👍

**Comment by pankti28** [comment]
Thank you @bensmiley. It was build error. I was trying to import the module which was not build properly , so unable to access the method of that module.
Now, its working fine. thanks for your support . :) :) 👍
