### ISSUE TITLE
Number of sections to display, need help ! 

### ISSUE THREAD

**Issue by jupiter0107** [chat-sdk/chat-sdk-ios#163]
Hi ben, thank you for answering my previous question on making changes to the UI directly, 

I would appreciate any help i can get from anyone in fact on the new issue that i am currently facing 

So i am trying to implement the group name change ability as you can see here however by adding this section i have also effected my private 1 on 1 chat as well 

as you can see in the screenshot below , this is for group chats
<img width="371" alt="screen shot 2017-12-08 at 8 15 26 pm" src="https://user-images.githubusercontent.com/34261628/33765665-ebc47010-dc54-11e7-8468-2c6fc05ac126.png">

and this happens on my 1 on 1 chat 
it should be showing the participants section instead. 

<img width="372" alt="screen shot 2017-12-08 at 8 20 50 pm" src="https://user-images.githubusercontent.com/34261628/33765754-527e54b0-dc55-11e7-8117-623c3ca98b34.png">

i am making changes in the BUsersViewController.m file 
Here are the changes that i've tried to make myself 

#define bGroupNameSection 0
#define bParticipantsSection 1
#define bAddParticipantSection 2
#define bLeaveConvoSection 3
#define bSectionCount 4

on my cellForRowAtIndexPath function i wrote this.

 ```
    if (indexPath.section == bGroupNameSection) {
        UITextField *groupNameTextField = [[UITextField alloc]initWithFrame:CGRectMake(10,10, 300, 30)];
        groupNameTextField.clearButtonMode = UITextFieldViewModeWhileEditing;
        groupNameTextField.text = _thread.displayName;
        [cell.contentView addSubview:groupNameTextField];
    }
```

Here is the number of sections in table view code

```
- (NSInteger)numberOfSectionsInTableView:(UITableView *)tableView {
    // We only show the add and leave group for private groups
    return _thread.type.intValue == bThreadTypePrivateGroup ? bSectionCount : 1;
   
}
```

is there a way i can make participants section to be displayed first while still keeping the groupName at the top of the table ?

**Comment by bensmiley** [comment]
The problem is that in a group chat, there are usually 3 sections (4 in your case) and in a private chat there is usually only one. 

You've essentially, added an extra section at the top and since you're still saying that there is only one section for private threads, that is the only one that is shown. 

There are two solutions:

1. Make the name change section not be the first section. Add it in as section number 1. 

2. Currently the logic is all based on the section number. So we decide which data to load `numberOfRowsInSection` based on the section number. We decide how to render the cells in `cellForRowAtIndexPath` also based on this number. If `section == bParticipantsSection` we will show the participants. But currently, the section is being equal to `bGroupNameSection`. To get around this we can just check if this is a private thread and if it is, we set the section to always be the `bParticipantsSection`.

  ```
  int section = privateThread? bParticipantsSection :  indexPath.section
  ```
  You would need to do this everywhere where the section is used.

**Comment by bensmiley** [comment]
@jupiter0107 Also, with this kind of issue, if you added this feature to a new branch it's the kind of thing we would integrate with the core library. That means that I could help you with the development and then it would receive fixes and updates going forward.
