### ISSUE TITLE
Anonymous login feature

### ISSUE THREAD

**Issue by GreenRollingHills** [chat-sdk/chat-sdk-ios#172]
I noticed that anonymous login was removed from the chatSDK app on the app store.  Are you planning on no longer supporting this feature?  Thanks.

**Comment by simonsmileyandrews** [comment]
Hi @GreenRollingHills,

The reason for this was because Apple discourages anonymous login on the Apple store. This meant we would have had to change the current state of the anonymous login to enable the app to be accepted. 

We will be continuing to support and enable the anonymous login feature in the ChatSDK but users wanting to use it in their applications will need to research which scenarios Apple allows and blocks. We will also be available to support any modifications which are needed to enable anonymous variations to pass on the app store. 

Simon

**Comment by GreenRollingHills** [comment]
Ok.  Thanks for your response.
