### ISSUE TITLE
Using This SDK for personal use and to push to appstore

### ISSUE THREAD

**Issue by alejandroSoftware** [chat-sdk/chat-sdk-ios#196]
Hello,

I understand that this app is MIT licensed
Is it possible for me to replicate this application, modify the UI a little and push it to the app store for my personal use? would i face compliance problems with this?, or would i be able to pass apple's app review in this case? 

Also i have read that the blocking feature is required to conform to apple's app review under the user generated content.  i would like to purchase the blocking feature to integrate it into my personal application, would that suffice into conforming to apple's app review? 

Has anyone else hit any roadblocks by using this SDK to push to the app store ? 

Thanks

**Comment by alejandroSoftware** [comment]
My other concern would be would i be rejected due to : 

4.1
Design Copycats (App Store, guideline 4.1) - the lack of app’s uniqueness in short

**Comment by bensmiley** [comment]
Hi Alejandro,

The project isn't actually MIT licensed. You can see details of the license [here](https://github.com/chat-sdk/chat-sdk-ios/blob/master/LICENSE.md). You would be allowed to replicate the application, modify the UI and push it to the app store for personal or commercial use under the Chat SDK license. 

With regards to the review procedure, this is really between you and Apple. We provide a messaging framework - the goal is to make it much easier for people to deploy instant messaging apps. However, we would expect people using the projects to review the Apple guidelines and ensure that their app meets them. I don't think being a copycat would be a problem since most messengers are very similar anyway. It's likely that you would need the blocking feature or some way to justify to Apple why it's not needed. 

In the past, people have had issues with not implementing a robust moderation procedure, not having a terms and conditions page and not implementing blocking. But it depends a lot on the app and who's reviewing it that day.
