### ISSUE TITLE
Replacing placeholder image in chat view when loading picture

### ISSUE THREAD

**Issue by chriseman** [chat-sdk/chat-sdk-ios#200]
Hi there,

Would it be possible to replace the placeholder image in the chat view with another asset when an image is being loaded?

**Comment by simonsmileyandrews** [comment]
Hi @chriseman,

The cells in the chat view are all subclassed from the BMessageCell. If you load up this file you should be able to see the _profilePicture variable. This is the one you want to access. 

If you open the BMessageCell.m file and look in the `setMessage` function you will see this code (I have removed some of the commented out code here):

```
    // We only want to show the user picture if it is the latest message from the user
    if (position & bMessagePositionLast) {
        if (message.userModel) {
            _profilePicture.hidden = NO;
            if(message.userModel.imageURL) {
                [_profilePicture sd_setImageWithURL:message.userModel.imageURL
                                   placeholderImage:message.userModel.defaultImage];
            }
            else if (message.userModel.imageAsImage) {
                [_profilePicture setImage:message.userModel.imageAsImage];
            }
            else {
                [_profilePicture setImage:message.userModel.defaultImage];
            }
        }
        else {
            // If the user doesn't have a profile picture set the default profile image
            _profilePicture.image = message.userModel.defaultImage;
            _profilePicture.backgroundColor = [UIColor whiteColor];
        }
    }
    else {
        _profilePicture.image = nil;
    }
```

This code checks whether the cell is the latest cell from the user and then sets the profile picture accordingly. 

You can see that we use this code a number of times:

```
message.userModel.defaultImage
```

This is fetching the default user image and using it to set the imageView. 

Now if we navigate to the CDUser.m file we can find the user default image function:

```
-(UIImage *) defaultImage {
    return [NSBundle imageNamed:bDefaultProfileImage framework:@"ChatSDK" bundle:@"ChatUI"];
}
```

We can also look in the BCoreDefines.h file to see the name of the default image:

`#define bDefaultProfileImage @"icn_100_anonymous.png"`

A quick way therefore to replace this image would be to

1. Create a new default image
2. Name it as above
3. Replace the current default image with your new image

This method might not be the best way as we do not recommend changing the ChatSDK itself. Changes should be made to your project instead. Classes should be subclassed and then modified so that when you pull new versions of the ChatSDK you don't lose any changes you have made. 

To get a definitive answer on how you should architect your project you'll have to wait for an answer from @bensmiley but the answer above should allow you to test out your own default image and also give you an idea of how we are setting this default image in the first place.

**Comment by chriseman** [comment]
cheers Simo I will give it a try
