### ISSUE TITLE
How can I install manually

### ISSUE THREAD

**Issue by esmeyo** [chat-sdk/chat-sdk-ios#21]
I have a problem with cocoapods and I want to use this SDK as it suits my needs.
How can I install the project manually?
Can you please specify which headers I need to drag into my project?
Thanks,
Esme

**Comment by bensmiley** [comment]
Hi Esme,

What's the problem you're having with Cocoapods? The problem with adding the project manually is that it relies on quite a few external libraries - which would all have to be added manually too. If you're having a problem with the `use_frameworks!` flag, you can look at this issue #11. 

Otherwise, I'd recommend running `pod install` on the default Chat SDK project and then dragging in the source code and frameworks to your project. 

You could also go through the Podspecs and add all of the library dependencies to your project's Podfile and then drag in the Chat SDK source code to your project.
