### ISSUE TITLE
Firebase chat with objective c language

### ISSUE THREAD

**Issue by iKambad3618** [chat-sdk/chat-sdk-ios#210]
i want to integrate firebase chat in my iPhone application with objective c language, i created new projects with all required pods and all. but at last it gives me error which i cant able to resolve. please help me out .. error would be like..
if([BChatSDK config].includeMessagePayload . no known class for config.
if([BChatSDK config].includeMessageJSON) includemessage.json not found

**Comment by bensmiley** [comment]
Could you try downloading the Firebase Network Adapter from [this location](https://github.com/chat-sdk/chat-sdk-ios/releases/tag/4.4.5)? I think that the issue is that the latest version of the code from Github is now not compatible with the cocoapod version so you should download the 4.4.5 snapshot.
