### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by ChintanWeapp** [chat-sdk/chat-sdk-ios#224]
I have implemented this to my project. The issue, I'm facing is when I logged-In to the app with another user from same device the PushToken in firebase database remains same for the users and so that when I am trying to send message to other user at that time I'm also receiving the notification. 

Is there any way to solve this or to clear the pushToken field when I'm going to logout from app ?

**Comment by jaybayley** [comment]
+1, we're having the same issue where users are receiving push notifications after logging out from the chat SDK. We were going to try to fix this (on iOS) by listening to the `bNotificationLogout` notification and manually removing the push token, but it's too late at this point as the user is no longer authenticated with Firebase.

Could we get this fixed in the SDK itself please?

**Comment by jimijon** [comment]
+1
