### ISSUE TITLE
chat search

### ISSUE THREAD

**Issue by chintanTBI** [chat-sdk/chat-sdk-ios#278]
I need to add the option to search the chat with users based on user name. Can any one help me out with this?

**Comment by bensmiley** [comment]
@chintanTBI do you mean you want to search for a particular conversation?

**Comment by chintanTBI** [comment]
Yes that's what exactly I am looking for

**Comment by ganico** [comment]
is this issue has been solved?

**Comment by bensmiley** [comment]
You would need to write your own code to do this and it may well not be possible due to the limitations of Firebase Realtime Database - the thread data is like this:

```
threads/[thread-ids]/users/[user-ids]
```
You can only search one level deep and the user id's are two levels deep. Plus you would need to somehow join the user's name which is stored at `users/[user-ids]/meta/name` to a different branch. 

You could either do this by creating a separate mapping index which maps user name to room id or you could use an external search library to index the data.

**Comment by bensmiley** [comment]
Ah ok, yes you can use offline filtration. I can think about implementing offline thread filtering.
