### ISSUE TITLE
User can change its email after Login without verification and validation

### ISSUE THREAD

**Issue by expertalex** [chat-sdk/chat-sdk-ios#30]
in the profile section you can change your email without any problems to other email without verification and/or validation. 
What if this email is already in use by other user?
The same happens with the Phone.

Normal Email and Phone have to be unique and the database shod enforce that.

**Comment by bensmiley** [comment]
The email field has no validation. It's just a piece of meta data that can be set by the user and it's not involved in authentication. That's why it doesn't need to be unique. We just added it as a demonstration of how fields can be set by the user and then indexed for the search functionality. 

If you want it to be unique, the easiest option would be not to allow the user to change the field manually and set it based on the Firebase user object after authentication.
