### ISSUE TITLE
Push notification received from blocked users

### ISSUE THREAD

**Issue by itimmisriis** [chat-sdk/chat-sdk-ios#315]
1. **Is the bug present in the demo Chat SDK project?**
N/A
2. **What modifications have you made to the Chat SDK?**
N/A

3. **iOS Version? Device or simulator?**
10.3, device

4. **Steps taken to reproduce the problem:**
Create 2 users. User A blocks user B. User B sends User A a message

5. **Expected result:**
User A should not receive push notification

6. **Actual result:**
User A should receives push notification

7. **Comments:**
This happens with Android SDK as well.

**Comment by alionako** [comment]
Probably you should modify your [index.js](https://raw.githubusercontent.com/chat-sdk/chat-sdk-ios/master/FirebasePushNotifications/index.js) file (from [this](https://github.com/chat-sdk/chat-sdk-ios#setup-firebase-cloud-functions) tutorial) so that it handles blocked users, too, and re-deploy it. For now it sends notifications to all the users that are in the given thread. (probably another option is to try deleting user from thread if he's blocking his opponent).
