### ISSUE TITLE
More Custom Sign in issues...

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#348]
I have the latest Firebase pods, the latest as of today Chat, and converted my project code to Swift 5. Now I am having an issue understanding custom signin.

Is there complete documentation for integrating a custom SignIn controller for Firebase?

In the example code you have it marked as TODO. I would like to understand because now it doesn't quite work. I used to just :

```
//Override SignIN
            let signInController = UIStoryboard(name: sbname, bundle: nil) .instantiateViewController(withIdentifier: "SignInViewController") as! SignInViewController
            BChatSDK.ui()?.setLoginViewController(signInController)
```

This brings up my view controller with a simple button to "log in", then this takes me to the Firebase Interface as before,,, but upon entering credentials it just backs me out again.

Was wondering if you had a working example or uptodate docs

**Comment by jimijon** [comment]
I also notice, though, that it doesn't dismiss my custom sign-in controller like it used to. But the next time I sign in since it is authenticated it shows the CHATSDK logo briefly before entering my app.

**Comment by jimijon** [comment]
I think it might have to do with that navigation controller:

                self.window?.rootViewController = BChatSDK.ui()?.splashScreenNavigationController()

**Comment by jimijon** [comment]
More info: I used to use:

            self.window?.rootViewController = BInterfaceManager.shared().a().appTabBarViewController();

to set my root as my custom tabbarviewcontroller class...  it says it is deprecated.

**Comment by jimijon** [comment]
ok, so I need some docs on the new flow here.  I tried to override the spashscreenviewcontroller but the call has "bit" arithmetic in it..?

    BChatSDK.ui()?.setSplashScreenViewController(controller: UIViewController & PSplashScreenViewController)

?? What is that doing?

**Comment by bensmiley** [comment]
@jimijon the login works a little differently now because we found that using a modal view for the login caused a lot of issues in certain circumstances and wasn't very flexible. 

Now the splash screen is responsible for either showing the login view controller if the user isn't logged in. Or showing the main view controller if they are. 

So you shouldn't need to dismiss the login view controller. The login view controller needs to authenticate with Firebase either by using the:

```
BChatSDK.auth authenticate: ... 
```

Methods or directly using the Firebase library. If you do it directly, you would need to call:

```
[BChatSDK.auth authenticate];
```

Afterward to setup the Chat SDK. 

After that the splash screen controller will intercept the user auth completed event and hide the login view controller and show the main view controller.

**Comment by jimijon** [comment]
thanks for the explanation. I have it all working again.
