### ISSUE TITLE
Getting Parse Issue Group in exciting project

### ISSUE THREAD

**Issue by Karthickkck** [chat-sdk/chat-sdk-ios#35]
Am using podfile to integrated but am getting Parse Issue Group in exciting project.
![screen shot 2017-04-20 at 6 21 00 pm](https://cloud.githubusercontent.com/assets/19325688/25231616/2321a7b4-25f6-11e7-834f-0d1a9216935c.png)
![screen shot 2017-04-20 at 6 21 00 pm](https://cloud.githubusercontent.com/assets/19325688/25231648/3d62a95c-25f6-11e7-936a-3998a3c0b055.png)

So , Please give me any solution

**Comment by simonsmiley64** [comment]
Hi @Karthickkck,

Can you confirm whether your project uses the use_frameworks flag in your podfile?

If it does you should download the use_frameworks_beta_2 branch instead of the master. We are going to be updating the master branch in the next few days with this but it might help fi your current problem. 

If this doesn't help let me know and we will further help troubleshoot the problem.

Simon

**Comment by Karthickkck** [comment]
Am using this link to install my existing project.
https://www.youtube.com/watch?v=oeQhIN9ut

am attached podfile screen shot 
![screen shot 2017-04-24 at 11 03 11 am](https://cloud.githubusercontent.com/assets/19325688/25323559/bb9c7f84-28dd-11e7-9a23-891c01ca6067.png)
vE

**Comment by bensmiley** [comment]
Can you checkout the branch `use_frameworks_beta_2` and add it to your project? You will need to add the following to your Podfile:

```
  pod "ChatSDKCore", :path => "../ChatSDK/ChatSDKCore"
  pod "ChatSDKUI", :path => "../ChatSDK/ChatSDKUI"
  pod "ChatSDKCoreData", :path => "../ChatSDK/ChatSDKCoreData"
  pod "ChatSDKFirebaseAdapter", :path => "../ChatSDK/ChatSDKFirebaseAdapter"
```

**Comment by simonsmiley64** [comment]
This branch has now been moved to master so this should no longer be an issue. If this issue reoccurs please create a new ticket for us to work on.

**Comment by Karthickkck** [comment]
Ya ok thanks
