### ISSUE TITLE
Get all users list from servers

### ISSUE THREAD

**Issue by salmene** [chat-sdk/chat-sdk-ios#393]
I am trying to integrate ChatSDK into my project, but I faced a problem for which I can't find any solution.
**The problem:**
I want to get all users from server, but `BChatSDK.contact()?.contacts()` return only the contact that already the user start discussion with.
So, my question is how to get all the users list, and how can I start a conversation with one of them or many (group)?

**Comment by bensmiley** [comment]
Hi @salmene this is quite a common question. Currently there is no way to get every user on the server. The reason is that although this seems like a good idea for a small amount of users, imagine if you had 500k users.. You definitely wouldn't want to download that data to every device because it would cost a massive amount in Firebase hosting. To access another user you can use the search API:

```
-(RXPromise *) usersForIndexes: (NSArray *) indexes withValue: (NSString *) value limit: (int) limit userAdded: (void(^)(id<PUser> user)) userAdded;
```

You would use it like this:

```
    [BChatSDK.search usersForIndexes:indexes withValue:text limit: 10 userAdded: ^(id<PUser> user) {

    }].thenOnMain(^id(id success) {
        return Nil;
    }, ^id(NSError * error) {
        return error;
    });
```

Or if you know the user's ID, you can use:

```
    [BApi userForEntityID: @"userId"].thenOnMain(^id(id<PUser> user) {
        
        return Nil;
    }, Nil);
```

**Comment by salmene** [comment]
Thanks @bensmiley for your response. But what are exactly these indexes?

**Comment by bensmiley** [comment]
The default indexes are `email`, `name` and `phone` but you can add extra custom indices.

**Comment by ganico** [comment]
is it possible to use that search and include the people that you haven't added? 
OR 
how to manage the contact list in firebase so we can maximize the search function that you have.

**Comment by bensmiley** [comment]
You can search for any user. But it should be a directed search - not a way to access all the users.
