### ISSUE TITLE
FirebaseUI conflicts with ChatSDKFirebaseAdapter podspecs

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#40]
I cannot get these two to coexist:

The 'Pods-TwoBitTrader' target has frameworks with conflicting names: firebaseanalytics.framework, firebaseauth.framework, firebasecore.framework, firebasedatabase.framework, firebaseinstanceid.framework, and firebasestorage.framework.

**Comment by jimijon** [comment]
I commented this line out of the pod spec and seems to work:

#  s.vendored_frameworks = "Frameworks/*"

**Comment by bensmiley** [comment]
The problem is that the Firebase pods aren't configured correctly for frameworks (this is a problem with the way Firebase have designed their pods). The result is that if you try to add the Firebase pods as a podspec dependency, the project won't compile. The only we've found to solve this is to build the Firebase pods using Carthage and then include them directly using vendored frameworks. 

The problem is that the pod you're trying to add probably includes the Firebase pods as a dependency so they are being added twice. Once to the ChatSDKFirebaseAdapter and once at the project level. 

Can you give me some more details about the pod you're trying to install?

**Comment by jimijon** [comment]
pod 'FirebaseUI', '~> 3.0'

**Comment by jimijon** [comment]
Never used Carthage. I don't see any instructions related to Carthage. Would you happen to have the pod file and cart file I could learn from?

**Comment by bensmiley** [comment]
If you look in the `ChatSDK` folder you'll see the `update_firebase_frameworks.sh` script. This script will automatically download and compile the Firebase libraries and then add them to the `ChatSDKFirebaseAdapter` pod. 

I'm going to have a look and see if we can include the Firebase pods directly. When I tried previously there were always issues with missing header files. I'll look at the `Firebase-UI` pod to see how they get around these issues.

**Comment by jimijon** [comment]
Please do review FirebaseUI pod spec. Be nice to get all of Firebase to work with chat via just pods.

**Comment by jimijon** [comment]
OK -

I just ripped Firebase out of the ChatSDKFirebaseAdaptor. 
Imported the classes directly into my project
Changed the imports, i.e., 
<ChatSDKFirebaseAdapter/ChatFirebaseAdapter.h> to "ChatFirebaseAdapter.h"

And it built and compiled!

**Comment by bensmiley** [comment]
Fixed in a8a0d690df379b62cb14cb18b05652e32ff32034 see instructions [here](https://github.com/chat-sdk/chat-sdk-ios#firebase-ui).
