### ISSUE TITLE
chatsdk on update gives error

### ISSUE THREAD

**Issue by vijay2102** [chat-sdk/chat-sdk-ios#439]
BChatSDK.shared.networkAdapter.socialLogin = [[BFirebaseSocialLoginHandler alloc] init];

**Comment by bensmiley** [comment]
We have removed social login support from the latest version of the Chat SDK. Since the social login APIs change very frequently and the libraries they use are very buggy, it became a big overhead to keep the social login working. Also, keeping the documentation up to date took a lot of time. Since Firebase UI already supports the same features, we decided to discontinue this feature. If you want to maintain it yourself, you are welcome to check out the code from the previous version and update the module to work with the latest Chat SDK version.
