### ISSUE TITLE
Can't receive notification in IOS13

### ISSUE THREAD

**Issue by SamQuest** [chat-sdk/chat-sdk-ios#446]
1. **Is the bug present in the demo Chat SDK project?**
May be or i am missing a preference setting
2. **What modifications have you made to the Chat SDK?**
NONE
3. **iOS Version? Device or simulator?**
iOS13
4. **Steps taken to reproduce the problem:**
Able to receive notification until iOS12 but not in iOS 13

FIRDataEventTypeChildAdded event is triggered in iOS13 but i need notification when the app is background which is not happening.

i do not use SceneDelegate. FIRAuth.m seems to check iOS13 and do something with SceneDelegate which i do not understated.

**Comment by SamQuest** [comment]
I am able to receive notification in iOS 12 and debugged many times in iOS13 and still not able to receive notification is there any pointers atleast where to start. i am not even getting events in notification delegate.

**Comment by bensmiley** [comment]
This kind of issue is usually caused by incorrect push setup. Notifications work on my iOS 13 device. You need to make sure all your provisioning profiles are setup correctly and the APS key is uploaded to Firebase. If this still doesn't work, try testing the app in TestFlight. Sometimes development profiles don't work for notifications.
