### ISSUE TITLE
ios unable to send image message from gallery or camera

### ISSUE THREAD

**Issue by ruchibukshete** [chat-sdk/chat-sdk-ios#508]
1. **Is the bug present in the demo Chat SDK project?**
No, I have integrated latest chat sdk in my app
2. **What modifications have you made to the Chat SDK?**
None
3. **iOS Version? Device or simulator?**
ios 16
4. **Steps taken to reproduce the problem:**
Click on send media in chat window -> the option pop ups for camera or gallery -> Select the desired option 
5. **Expected result:**
It should navigate to the screen to edit the image 

6. **Actual result:**
    1. The screen gets stuck after the image is selected from gallery
   2. When opened through camera the screen gets stuck after the image is clicked
7. **Comments:**

**Comment by bensmiley** [comment]
Tested on the latest version and this issue does not appear.

**Comment by mahesh-ivy** [comment]
@bensmiley  i am getting this problem... the log says below.

Attempt to present <TOCropViewController: 0x10e8f5e00> on <UINavigationController: 0x10e80d800> (from <BChatViewController: 0x115809000>) which is already presenting <UIImagePickerController: 0x10e1de000>.

I think just after image is selected, when you are trying to present the cropper view controller, you are doing it without dismissing the picker. Thats why this issue is happening. I have also tried to create my own interface adapter to override the chatOptions function to disable the cropping option for image picker or camera but when i do that, the image is being sent to the other person as soon as i select the image but the picker is not getting dismissed. When i click image and click cancel, what i observe is that image is sent. Please check this issue.. Happening on latest version 5.2.2. 

Also one big concern about your this library is there is no documentation given for customisation like you have for the android chat SDK. The guide for customising things would help a lot.

Thanks.

**Comment by ruchibukshete** [comment]
Hello @mahesh-ivy , I have fixed this issue in my following fork,
https://github.com/ruchibukshete/chat-sdk-ios.git

**Comment by mahesh-ivy** [comment]
@bensmiley  please accept the merge request for this problem from @ruchibukshete . thank you. this issue is there for sure.
