### ISSUE TITLE
Audio Messages module isn't working

### ISSUE THREAD

**Issue by RyanElliott94** [chat-sdk/chat-sdk-ios#59]
Right so when i do the necessary steps to install the module i get an error saying BAudioMessageCell.h is missing despite it being in finder.

Anyone have any ideas as to why this is happening?

Ryan

**Comment by simonsmiley64** [comment]
A few questions:

- Have you gone through the ReadMe completing each step?
- Have you added the audio module to the podfile correctly?
- Have you called pod install?

If the answer to all these is yes then let me know and I will help troubleshoot further

Simon

**Comment by RyanElliott94** [comment]
Yeah I've done all that but it still wouldn't work unfortunately

Ryan

**Comment by RyanElliott94** [comment]
Hello @simonsmiley64 Unfortunately I'm still having an issue with this,

I've tried and tried again to install the module but it's still not working. I've gone through every instruction that i can find but nothing. 

If I'm honest its a little confusing when it comes to the instructions because one minute it says that the ChatSDKFirebase folder along with the AudioMessages should go in ChatSDK/ChatSDKFirebase but the folder is actually outside of the ChatSDK folder but then it also says, like when installing the pod that it actually has to be ChatSDKFirebase/AudioMessages!

Now installing the actual pod isn't exactly the issue, the main thing is that i get nothing but errors saying it can't find files. Such as BMessageCell.h and when you uncomment `import <ChatSDKFirebase/AudioMessages>` from the BModules.h it again says it cannot be found so I'm completely confused.

Thanks
Ryan

**Comment by RyanElliott94** [comment]
I don't want to be annoying but i really need this sorted!

Thanks

**Comment by CalvinTp** [comment]
Hi Ryan,

I manage to get the Audio module working and let me share my steps here in case it might help. Btw, I am directly installing this in the Xcode module (which is the Chat Demo provided by Ben, Simon and co). 

The steps below is exactly the same as the README.md provided along with the module except the confusion of "Add the folder `AudioMessages` to `ChatSDK/ChatSDKFirebase`". I also noticed that ChatSDKFirebase folder is in parallel with ChatSDK folder. I believe this line in the tutorial needs to be cleaned up into "Add the folder `AudioMessages` to `ChatSDKFirebase`" instead, then everything would work perfectly. 

I copied the entire AudioMessages folder and placed it under ChatSDKFirebase folder. The ChatSDKFirebase folder is in parallel with the Xcode folder. 

Goto your Xcode pod file (Podfile) and add the following line:
  pod "ChatSDKFirebase/AudioMessages", :path => "../ChatSDKFirebase"

Go back to the Xcode folder and run pod install. 

After that, add the following lines in your AppDelegate.m file, and they have actually provided the places for you to add these lines already so you can just uncomment those which are applicable. 

Add Line 1>>>#import <ChatSDKFirebase/AudioMessages.h>
Add Line 2>>> [[[BAudioMessageModule alloc] init] activate];

Thanks,
Calvin

**Comment by CalvinTp** [comment]
Hi Ryan,
Another thing to note is that the pod file needs to be (which comes with the README):
pod "ChatSDKFirebase/AudioMessages", :path => "../ChatSDKFirebase"

instead of (that is commented line in the existing Podfile):
#   pod "ChatSDKFirebase/AudioMessages", :path => "../../ChatSDK/ChatSDKFirebase"

Perhaps someone can update these "commented line" in Xcode pod incase someone did not notice the subtle different. 

Thanks,
Calvin

**Comment by RyanElliott94** [comment]
It's still not working, still getting errors. I've even tried setting up the whole project again but still didn't work so I'm out of ideas.

Thanks for the help though!

Ryan

**Comment by CalvinTp** [comment]
Hi Ryan,
Just to check, the steps to uncomment the import inside the BModules.h are not supposed to be there.

From your earlier comment:
"_when you uncomment import <ChatSDKFirebase/AudioMessages> from the BModules.h it again says it cannot be found so I'm completely confused._"

Therefore there is no need to change anything in the BModules.h file to get the Audio Module working. Btw, what errors are you facing other than the one you listed above? 

Thanks,
Calvin

**Comment by simonsmiley64** [comment]
1. Copy in Audio folder into the ChatSDKFirebase folder in the Chat SDK
2. Add the path to the Audio folder in **your projects** podfile. If you have a podfile for your project you need to add it to this and not the podfile in the Chat SDK project.
3. In the Chat SDK project it is this:   

```
pod "ChatSDKFirebase/AudioMessages", :path => "../ChatSDKFirebase"
```

You can read a tutorial about configuring this path in your project [here](https://github.com/chat-sdk/chat-sdk-ios/wiki/Chat-SDK-iOS:-How-do-I-link-my-podfile%3F)

4. Call `pod install`
5. Add the audio code in **your project's** app delegate:

```
#import <ChatSDKFirebase/AudioMessages.h>

[[[BAudioMessageModule alloc] init] activate];
```

I have just done this on a downloaded version of the Chat SDK and it compiles without an error, the audio messages are also working as expected. 

<img width="250" alt="screen shot 2017-05-29 at 16 47 47" src="https://cloud.githubusercontent.com/assets/8721425/26555766/913c6106-448e-11e7-98ae-c4df17fb845f.png">

I would expect therefore that there is a step which you are not doing correctly, it might be that you are adding the code to the Chat SDK podspec instead of your own or that you are not linking the path from your podfile to the Audio folder correctly.

If you can add a screenshot of your folder structure showing the podfile and the ChatSDK as well as what you are adding in your podfile I can help see if this is the problem.

Simon

**Comment by RyanElliott94** [comment]
I've tried every single thing I've been told so i don't know what's going on! 

But anyway, here is the folder structure:
<img width="859" alt="screen shot 2017-05-29 at 18 09 44" src="https://cloud.githubusercontent.com/assets/7635526/26557582/6451f154-449a-11e7-8808-74ae330f950c.png">

And the  podfile:
<img width="568" alt="screen shot 2017-05-29 at 18 11 11" src="https://cloud.githubusercontent.com/assets/7635526/26557598/85bcae2e-449a-11e7-832e-73e96fc58b4e.png">

**Comment by simonsmiley64** [comment]
Hi @RyanElliott94,

Hi have emailed you the latest version of the code in case you are using a depreciated version considering you bought the license in March,

Let me know if this fixes the problem otherwise we will continue to troubleshoot,

Simon

**Comment by RyanElliott94** [comment]
@simonsmiley64  Has the email been sent to the email on my profile? because i haven't received it yet 

Ryan

**Comment by RyanElliott94** [comment]
Thank you @simonsmiley64! It's all working now!
