### ISSUE TITLE
327 errors after build and run

### ISSUE THREAD

**Issue by RogerRabbit91** [chat-sdk/chat-sdk-ios#66]
I followed the YouTube tutorial on starting this project and when I build it I get 327 errors. I tried to delete everything and start over and got the same errors. I don't know what I'm doing wrong.

**Comment by RogerRabbit91** [comment]
Anyone?

**Comment by simonsmiley64** [comment]
Hi @RogerRabbit91,

Can you post some information about the errors you are receiving? A screen shot would be great. Also can you confirm whether the Chat SDK runs correctly without configuring it at all (download and run)

Simon

**Comment by RogerRabbit91** [comment]
All of the errors are with the PromiseKit.

**Comment by simonsmiley64** [comment]
Hi @RogerRabbit91,

Without some information on the errors you are getting I cannot begin to troubleshoot the problem you are having. 

One fix might be updating the Swift syntax in your project. Click:

`Edit -> Convert -> To current Swift syntax...` 

Then select all the frameworks available and click `convert`. When this completes click `update`.

Once this has completed clean your project: `Product` -> `Build`

The reason I suggest this is because of the large number of errors being seen. If you can provide the answer to these questions it would help:

+ Can send me a screenshot of the errors you are receiving? 
+ Can you confirm when this error occurs? Is it after you have called `pod install` or during another part of the process. 
+ Are you using Swift or iOS?

Simon
