### ISSUE TITLE
Trying to import GoogleMobileAds into BchatViewController but header is not found 

### ISSUE THREAD

**Issue by Absentia** [chat-sdk/chat-sdk-ios#75]
I'm working on adding AdMob banner ads to my public chat rooms.  The newest version of the AdMob SDK is in my "Pods" file, but when I add #import <GoogleMobileAds/GADBannerView.h> to the chat room viewController it says that the header file can't be found.  It's confusing because I have GoogleMobileAds imported into other files in my project and it works fine.

**Comment by bensmiley** [comment]
Are you modifying the Chat SDK framework or are you subclassing the view controller? If you have added the banner view pod to your main project, it won't be available to the Chat SDK libraries.

**Comment by Absentia** [comment]
Well as you can probably tell I'm an extremely amateur coder, so this may be asking too much, but how would you recommend going about adding banner ads to the top of the public chatrooms?

**Comment by CalvinTp** [comment]
Hi Ben, Simon,

Since ChatSDK has manually add the GoogleMobileAds.framework under ChatSDKFirebaseAdapter (and other libraries such as GoogleSignIn, Twitter, etc), can you advise how could we access these libraries inside ChatSDKUI. 

There is no issue to use these libraries inside ChatSDKFirebaseAdapter which we could directly them use them, however we need access to these libraries outside of ChatSDKFirebaseAdapter.

I believe this is the issue faced by @Absentia and I am interested to know this as well since I need access to add Google Ads in ChatSDKUI. 

Thanks,
Calvin

**Comment by bensmiley** [comment]
Now google ads can just be imported in the main Podofile.
