### ISSUE TITLE
When a 1-to-1 thread is deleted then re-created, a new thread is created

### ISSUE THREAD

**Issue by bensmiley** [chat-sdk/chat-sdk-ios#81]
Delete 1-to-1 thread
Start new chat with same user
new thread created (when old one should be used)

**Comment by RyanElliott94** [comment]
I've only just realised it done this but I've just had a look at how threads are recovered on the android version of the SDK and it looks like before you create a thread, it will look through the Firebase database first to see if there's any existing threads and then it'll create it with all the messages and the deleted value removed.

Do you reckon that would work on the iOS version?

P.S Only looking because the problem makes my two thread delete methods rather pointless
