### ISSUE TITLE
Message Stickies won't compile

### ISSUE THREAD

**Issue by jimijon** [chat-sdk/chat-sdk-ios#88]
/Users/James/Documents/Development/INDX420/ChatSDKModules/StickerMessages/Classes/BStickerMessageHandler.m:31:20: No setter method 'setThread:' for assignment to property

Is there a new version? How do I get or learn about new versions of the paid modules?

**Comment by bensmiley** [comment]
I'll get this fixed on Monday.

**Comment by CalvinTp** [comment]
Hi Ben,
Other modules are also failing as well, however I have temporarily fixing the modules at my side from reading at the changes in the base code. 

For example in the BFirebaseAudioMessageHandler, i have changed the code below:

    //message.thread = [[BStorageManager sharedManager].a fetchEntityWithID:threadID withType:bThreadEntity];
    id<PThread> thread = [[BStorageManager sharedManager].a fetchEntityWithID:threadID withType:bThreadEntity];
    [thread addMessage: message];


Thanks,
Calvin

**Comment by jimijon** [comment]
@CalvinTp seems like your solution "instantly" adds the sticker to the conversation instead of into the entry/edit of the message

**Comment by CalvinTp** [comment]
Hi @jimijon , I didn't have the sticker modules therefore I am unable to share with you the solution specifically for sticker module. 

What I shared is how I work around the compilation issue in other modules. The method for message.thread usage in other modules has been deprecated based on the latest code release (since there is no setter for setThread), so I replace them based on the example I have given and it solved all my issues. 

If I have the sticker modules, I could help you out, unfortunately I am not using it currently so I didn't get the licence for my current app development.

**Comment by bensmiley** [comment]
This is now fixed.
